[workspace]
members = [
]

[package]
name = "ltheory"
authors = ["Limit Theory Redux Team"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "libphx"
path = "src/libphx/mod.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
path = "src/Main.rs"
name = "Main"

[dependencies]
libc = "0.2"
stb = "0.3.2"
sdl2-sys = { version = "0.35.2", features = ["bundled", "static-link"] }

[build-dependencies]
cmake = "0.1"