[workspace]
resolver = "2"
members = ["engine/bin/*", "engine/lib/*"]

[workspace.package]
version = "0.1.0"
authors = ["Limit Theory Redux Team"]
edition = "2021"
license = "Unlicense"

[workspace.dependencies]
# workspace bin crates
ltr = { path = "engine/bin/ltr" }

# workspace lib crates
phx = { path = "engine/lib/phx" }
fmod-sys = { path = "engine/lib/fmod-sys" }
luajit-ffi-gen = { path = "engine/lib/luajit-ffi-gen" }
