[workspace]
members = [
]

[package]
name = "LimitTheoryRedux"
authors = ["LTR Team"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "libphx"
path = "src/libphx/mod.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
path = "src/Main.rs"
name = "Main"

[dependencies]
libc = "0.2"
stb = "0.3.2"

[build-dependencies]
cmake = "0.1"