[package]
name = "fmod-sys"
authors = ["Limit Theory Redux Team"]
version = "2.2.8"
publish = false
edition = "2021"
autobins = false

[build-dependencies]
bindgen = "0.53.3"
zip-extract = "0.1.2"
reqwest = { version = "0.11", features = ["blocking"] }
