[package]
name = "fmod-sys"
authors = ["Limit Theory Redux Team"]
version = "2.2.8"
publish = false
edition = "2021"
autobins = false

[build-dependencies]
bindgen = "0"
zip-extract = "0.1.2"
ureq = "2.6.2"
