name: Build Binaries (Pull Request)

on:
  pull_request:

env:
  BUILD_TYPE: RelWithDebInfo

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: nelonoel/branch-name@v1
        run: echo ${BRANCH_NAME}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Update build number
        run: |
          sed -i 's/Config.gameVersion = \".*\"/Config.gameVersion = \"${ BRANCH_NAME }${{ steps.vars.outputs.sha_short }}\"/' "${env:GITHUB_WORKSPACE}/script/Config/App.lua"
      - name: Build
        shell: bash
        run: ./build.sh
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-win32
          path: ${{github.workspace}}/bin/*
      - name: Upload binary with assets
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-distro-win32
          path: |
            ${{github.workspace}}/bin/*
            !${{github.workspace}}/bin/*.pdb
            ${{github.workspace}}/docs/*
            ${{github.workspace}}/engine/lib/phx/script/*
            ${{github.workspace}}/res/*
            ${{github.workspace}}/script/*
            ${{github.workspace}}/LICENSE
            ${{github.workspace}}/README.md

  build-macos:
    name: Build macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./build.sh
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-macos
          path: ${{github.workspace}}/bin/*

  build-ubuntu:
    name: Build Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update packages
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libudev-dev
      - name: Build
        run: ./build.sh
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-ubuntu2004
          path: ${{github.workspace}}/bin/*
